language: node_js
node_js:
  - "8"
script:
  - npm run build
after_success:
  - cd public; zip -r ../wecodetheweb.zip *
  - "curl -F 'data=@wecodetheweb.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: wecodetheweb' https://carehr.nl/deploy/"
