language: node_js
node_js:
  - "7"
cache: yarn
script:
  - yarn run build
  - node ./optimize-images.js
  - ./node_modules/.bin/hexo generate
after_success: ./node_modules/.bin/gulp deploy --user $FTP_USER --password $FTP_PASSWORD
