# Site
title: We code the web
subtitle: Brainfood for front-end developers
description: A blog about front-end/web development, brainfood for front-end developers.
author: Niels Gerritsen
language: English
locale: en_EN
type: blog

# URL
url: http://wecodetheweb.com
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: true
  line_number: false
  wrap: false
  hljs: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 8
pagination_dir: page

# Extensions
theme: wecodetheweb

